### ISSUE TITLE
Provide option to use --package instead of --packageVersion in the create-release call

### ISSUE THREAD

**Issue by jkane-variant** [variant-inc/actions-octopus#18]
We have a bunch of duplicated bash scripts across our entity-import repositories that are used by octopus processes during deploy steps. We would like to collect those scripts into a single repository, and publish that repository as a package in octopus. That way each service deployment can pull the latest version of our entity-import process step scripts directly from the referenced scripts package, instead of using the scripts embedded in the service package. 

It seems like this is doable outside of one piece. The current octopus action sets the package version for the release using `--packageVersion`. This uses the value submitted in that argument as the version number for *all* packages referenced by the release. In a scenario where a project might have an auxiliary package that contains tooling that is versioned independently of the main release package, octopus would also search for a version of the auxiliary package with the same version number as the main release package. This would most likely not exist, because the auxiliary package is maintained outside of this specific repository. 

The alternative to this is `--package`, where you can provide the version number for a specific package name. Based on the [docs](https://octopus.com/docs/octopus-rest-api/octopus-cli/create-release#option-package), it appears that octopus will default to the latest version of any package not provided by a `--package` argument, which is exactly what we'd want for this feature. 

The octopus action would provide the `--package` argument for the main release package, using the same value as the created package in the `push` step, but any auxiliary packages included in the process steps for the release would use the latest version in that package feed.

**Comment by jkane-variant** [comment]
@vibindaniel @hpatel826 @anr-variant

**Comment by vibindaniel** [comment]
@jkane-variant Please create a JIRA ticket

**Comment by jkane-variant** [comment]
I can, but didn't know if we wanted to discuss things here first

**Comment by vibindaniel** [comment]
@jkane-variant It is easier to have all conversations at one place. We can discuss in slack :). @hpatel826 is working on something that will remove all the deployment scripts across all repositories. We can include yours in that.

**Comment by jkane-variant** [comment]
alrighty, will close this
